### PR TITLE
Enable build for Ubuntu 22.04, x86-64

### PR DESCRIPTION
**Pull request by bdbcat**

### CODE REVIEW

**Comment by jongough** [comment]
I have incorporated your changes into FE2. I did not accept your pull request as I needed to do the changes to PluginConfigure.cmake differently. I changed line 149 rather than adding the lines you did. 

I would like to remove all the 'tuple' stuff from the <target > tag and replace it with extra targets that describe the build and run environments the build supports. The inclusion of gtk version and wxWidgets versions in the tuple is very difficult to support from a build perspective particularly if it is used as a template and the builds keep on changing. This is the issue I have mentioned multiple times, but....

**Comment by bdbcat** [comment]
Jon...
That seems fine, as long as the build products for Jammy (22.04) do NOT contain the "-gtk3" element in the name or metadata, as required by Ubuntu 22.04 build of OCPN core.

Not fully understanding your second para comment.   But I'll wait to see your solution.

**Comment by jongough** [comment]
This is what it looks like in the alpha cloudsmith (it is in the beta as well) and I will submit the pull requests for plugins.

```<?xml version="1.0" encoding="UTF-8"?>
<plugin version="1">
<name> Testplugin </name>
<version> 1.0.211.0 </version>
<release> 0 </release>
<summary> Plugin to test examples of the ODAPI and JSON interface for ODRAW </summary>

<api-version> 1.16 </api-version>
<open-source> yes </open-source>
<author> Jon Gough </author>
<source> https://github.com/jongough/testplugin_pi </source>

<description>
testplugin Plugin is used to test out the ODraw API and demonstrate how to use it successfully from another plugin
</description>

<target>ubuntu-x86_64</target>
<build-target>ubuntu</build-target>
<build-gtk>gtk3</build-gtk>
<target-version>22.04</target-version>
<target-arch>x86_64</target-arch>
<tarball-url>
https://dl.cloudsmith.io/public/opencpn/testplugin-alpha/raw/names/testplugin_pi-1.0.211.0-ubuntu-x86_64-22.04-jammy-tarball/versions/1.0.211.0+9568.5cb3314/testplugin_pi-1.0.211.0-ubuntu-x86_64-22.04-jammy.tar.gz
</tarball-url>
<info-url> https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:safety:odraw1.6_pi </info-url>
</plugin>
```
From a plugin coding perspective and a template maintainer I would have thought the test would have been:
```
<target>ubuntu</target>
<build-target>ubuntu</build-target>
<build-gtk>gtk3</build-gtk>
<target-wxver>3.12</target-wxver>
<target-version>22.04</target-version>
<target-arch>x86_64</target-arch>
```
This then enables build scripts to be updated easily and it doesn't matter whether the target only has 'gtk2' or 'gtk3' the name is still the same. The build environment is maintained in the XML in simple tags and convoluted processing, and hence errors, will be reduced. We have already had issues with the 'tuple' being difficult to get correct and it requires developers to know every platform that is being used for deployment. I did successfully build 22.02 for gtk2, not sure it would run, but... Platform capabilities are determined at build time not at config time.

Your change should have just been limited to the extra lines in config.yaml and not in the cmake build process. This allows developers to add/change environments more easily without having to know the ins and outs.

If we have to use XML and JSON lets take advantage of it and not just the overhead.

Regardless, the runtime needs testing.

**Comment by rgleason** [comment]
Thumbs up

**Comment by jongough** [comment]
All the XML changes are backwards compatible. You may notice that FE2 is using some of the 'deprecated' tags. We should continue to use tipped on the current OCPN release and discuss where to go for the next one. It is easy to add optional tags so they can be built and tested and then OCPN can use them first rather than the current method. An informed decision can then be made.

**Comment by rgleason** [comment]
Added a Discussion in Opencpn https://github.com/OpenCPN/OpenCPN/discussions/2725

**Pull request closed without merging**
