### PR TITLE
Drop support for Buster/Bionic builds

### PR DESCRIPTION
**Pull request by nohal**
- Debian Buster is EOL since 2022 and there are 2 newer stable releases available 
- Ubuntu Bionic is past end of standard support since June 2023 and there are 2 newer LTS release available

### CODE REVIEW

**Comment by nohal** [comment]
These old platforms are past dead, just drop them, that is all the effort they deserve.

**Comment by jongough** [comment]
All bionic and buster builds, except currently armhf-1804-buster (raspbian), have been removed. Just going through build process.

**Comment by jongough** [comment]
This update incorporates your changes, or intent, that you made to ODraw. I will update OD with this version of Testplugin (FE2 build) as I try to keep them in sync so that Rick can use FE2 for his builds and has all modifications included.
Thanks for your input.

**Comment by rgleason** [comment]
Jon, I think this should be closed. I think you should do it. I can't.

**Comment by jongough** [comment]
Bionic and Buster removed from circleci builds

**Pull request closed without merging**
